version: "3"

services:
  queue:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./definitions.json:/etc/rabbitmq/definitions.json
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_management &&
               rabbitmq-server --load_definitions /etc/rabbitmq/definitions.json"

  trucker-tcp:
    build: .
    ports:
      - 7700:7700
    depends_on:
      - queue
volumes:
  rabbitmq-data:
