version: "3"

services:
  queue:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./definitions.json:/etc/rabbitmq/definitions.json
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_DEFAULT_PASS}
    command: >
      rabbitmq-server --load_definitions /etc/rabbitmq/definitions.json
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  trucker-tcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trucker-tcp
    ports:
      - "7700:7700"
    depends_on:
      queue:
        condition: service_healthy
    environment:
      TRUCKER_HOST: ${TRUCKER_HOST}
      TRUCKER_PORT: ${TRUCKER_PORT}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_QUEUE_NAME: ${RABBIT_QUEUE_NAME}
      RABBIT_DEFAULT_USER: ${RABBIT_DEFAULT_USER}
      RABBIT_DEFAULT_PASS: ${RABBIT_DEFAULT_PASS}

volumes:
  rabbitmq-data:
